#!/usr/bin/env python3
"""Deterministic per-process shard bridge for the PSRR `klt sim` grid (issue #99).

    shard.py gen   --workdir DIR [--batch-pdk-root /opt/pdk]
    shard.py merge --manifest DIR/shards.json -o merged.sim.json mos_tt=r1.json mos_ss=r2.json ...

Why this exists. The fleet runner image pins klt 0.5.0 (2AMLogic/2am#2193).
psrr.request.json needs three things that runner cannot carry in one request:
per-section corner libraries of the `{"lib","section"}` object form (the
fixed cornerCAP.lib cap_typ section of every process bundle),
`options.osdi_preload`/`stage_model_inputs`, and (client side) the netlist's
`.include` closure. This bridge splits the SAME 45-point grid into five
per-process requests that the 0.5.0 runner does run:

* `models.lib` = cornerMOSlv.lib, `corners.process` = [one bare section];
* the cornerCAP.lib cap_typ selection becomes a body-level selection `.lib`
  card against the image's baked PDK root;
* the OSDI libraries load from a body `.control` block's `pre_osdi` cards (the
  documented deviation from the netlist-body contract; sg13g2-bandgap's
  sim/harness proved it) because `osdi_preload` is dropped by the 0.5.0 runner;
* the DUT netlist is inlined into the shard body (the 0.6.0 submitting client
  uploads the body file only), preserving every element line verbatim;
* the print-precision settings of `ngspice_init` become `set` cards in the same
  `.control` block.

Nothing else changes: same measurements, same limits, same analysis, same
temperature and supply axes, default solver tolerance (DR-0005).

`merge` is a pure, validation-gated transform: it concatenates the five
reports in canonical grid order and recomputes only the aggregate counts. It
refuses (exit 2) a missing, duplicate or unexpected shard, a shard whose
request digest differs from the manifest's, a shard whose corners are not
exactly its nine expected (process, temperature, VDD) points, and any point
duplicated across shards. No corner or measurement value is edited. The merged
file must still pass `compare.py validate` before run.sh writes it.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import os
import re
import sys
from typing import Dict, List, Tuple

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import compare as C  # noqa: E402

MODEL_LIB_REL = "libs.tech/ngspice/models/cornerMOSlv.lib"
CAP_LIB_REL = "libs.tech/ngspice/models/cornerCAP.lib"
OSDI_FILES = ("psp103.osdi", "psp103_nqs.osdi", "mosvar.osdi", "r3_cmc.osdi")
INCLUDE_RE = re.compile(r"^\s*\.include\s+(\S+)\s*$", re.IGNORECASE)
DUT_INCLUDE = "../../../design/netlist/opamp_core.spice"
# Request options the 0.5.0 runner cannot honour (dropped or rejected there).
RUNNER_UNKNOWN_OPTIONS = ("osdi_preload", "stage_model_inputs", "ngspice_init", "fail_on_diagnostic")


class ShardError(Exception):
    """Shard set unusable (exit 2)."""


def _digest(obj) -> str:
    return hashlib.sha256(json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def shard_keys(process: str) -> List[C.Key]:
    return [k for k in C.expected_keys() if k[0] == process]


def build_body(body_text: str, dut_text: str, process: str, batch_pdk_root: str, init_cards: List[str]) -> str:
    """Shard body: control block, inlined DUT, cap selection card, bench elements."""
    inc = [ln for ln in body_text.splitlines() if INCLUDE_RE.match(ln)]
    if len(inc) != 1 or INCLUDE_RE.match(inc[0]).group(1) != DUT_INCLUDE:
        raise ShardError(f"body must carry exactly one include of {DUT_INCLUDE}, found {inc}")
    dut_lines = [ln for ln in dut_text.splitlines() if ln.strip().lower() != ".end"]
    models = f"{batch_pdk_root}/ihp-sg13g2/libs.tech/ngspice"
    ctrl = [".control"] + [f"pre_osdi {models}/osdi/{f}" for f in OSDI_FILES] + list(init_cards) + [".endc"]
    out: List[str] = [
        f"* SHARD BODY for {process} -- generated by sim/cmrr-psrr/klt/shard.py; do not edit.",
        "* Deviations from tb_psrr.body.spice, all forced by the klt 0.5.0 fleet runner",
        "* (2AMLogic/2am#2193), none changing the circuit or the measurement:",
        "*  - .control pre_osdi + print-precision cards replace options.osdi_preload/ngspice_init;",
        "*  - the DUT netlist is inlined in place of its .include (its .end line dropped);",
        "*  - cornerCAP.lib cap_typ is selected by a body-level .lib card (the runner's",
        "*    per-section corner libraries cannot carry the object form).",
        *ctrl,
    ]
    for ln in body_text.splitlines():
        if INCLUDE_RE.match(ln):
            out.append("* ---- begin inlined design/netlist/opamp_core.spice ----")
            out.extend(dut_lines)
            out.append("* ---- end inlined design/netlist/opamp_core.spice ----")
            out.append(f'.lib "{models}/models/cornerCAP.lib" cap_typ')
        else:
            out.append(ln)
    return "\n".join(out) + "\n"


def build_request(master: dict, process: str, body_name: str) -> dict:
    procs = [p["name"] for p in master["corners"]["process"]]
    if process not in procs:
        raise ShardError(f"{process} is not a process of the master request")
    req = copy.deepcopy(master)
    req["_comment"] = [
        f"Per-process shard of psrr.request.json for the klt 0.5.0 fleet runner: process {process} x 3 T x 3 VDD = 9 corners.",
        "Generated by sim/cmrr-psrr/klt/shard.py; the master request documents the full grid and the ratified-bound encoding.",
    ]
    req["netlist"] = body_name
    req["models"] = {"pdk": master["models"]["pdk"], "lib": MODEL_LIB_REL}
    req["corners"]["process"] = [process]
    for opt in RUNNER_UNKNOWN_OPTIONS:
        req["options"].pop(opt, None)
    return req


def _init_cards(master: dict) -> List[str]:
    cards = master["options"].get("ngspice_init") or []
    if any(not re.fullmatch(r"set \w+=\d+", c) for c in cards):
        raise ShardError(f"ngspice_init carries a non-`set` card the bridge cannot translate: {cards}")
    return list(cards)


def gen(workdir: str, batch_pdk_root: str) -> dict:
    with open(os.path.join(HERE, "psrr.request.json")) as f:
        master = json.load(f)
    with open(os.path.join(HERE, master["netlist"])) as f:
        body_text = f.read()
    with open(os.path.normpath(os.path.join(HERE, DUT_INCLUDE))) as f:
        dut_text = f.read()
    os.makedirs(workdir, exist_ok=True)
    manifest = {"master_request_sha256": _digest(master), "batch_pdk_root": batch_pdk_root, "shards": []}
    for proc in C.PROCESSES:
        body_name = f"body-{proc}.spice"
        body = build_body(body_text, dut_text, proc, batch_pdk_root, _init_cards(master))
        req = build_request(master, proc, body_name)
        with open(os.path.join(workdir, body_name), "w") as f:
            f.write(body)
        req_path = f"request-{proc}.json"
        with open(os.path.join(workdir, req_path), "w") as f:
            json.dump(req, f, indent=2)
            f.write("\n")
        manifest["shards"].append({
            "process": proc, "request": req_path, "body": body_name,
            "request_sha256": _digest(req), "body_sha256": hashlib.sha256(body.encode()).hexdigest(),
            "keys": [C.key_str(k) for k in shard_keys(proc)],
        })
    check_manifest(manifest)
    with open(os.path.join(workdir, "shards.json"), "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    return manifest


def check_manifest(manifest: dict) -> None:
    """The five shards partition exactly the 45 ratified points."""
    seen: List[str] = []
    for s in manifest["shards"]:
        seen.extend(s["keys"])
    want = [C.key_str(k) for k in C.expected_keys()]
    if sorted(seen) != sorted(want) or len(set(seen)) != 45:
        raise ShardError("manifest shards do not partition the 45 ratified points")


def rollup(specs: List[dict], corners: List[dict]) -> List[dict]:
    """Per-measurement rollup over all corners, klt sim's own rule (sim.py
    `_measurement_rollup`): error beats fail beats pass; worst case is the
    smallest margin, an absent margin worst of all, first corner wins ties."""
    out = []
    for spec in specs:
        name = spec["name"]
        entries = []
        for c in corners:
            for m in c["measurements"]:
                if m["name"] == name:
                    entries.append((c, m))
                    break
        sts = {m["status"] for _, m in entries}
        agg = "error" if "error" in sts else "fail" if "fail" in sts else "pass"
        worst, wkey = None, None
        for c, m in entries:
            key = m.get("margin") if m.get("margin") is not None else float("-inf")
            if worst is None or key < wkey:
                wkey = key
                worst = {"corner_id": c["corner_id"], "value": m["value"], "margin": m.get("margin")}
        out.append({"name": name, "unit": spec.get("unit"), "limits": spec.get("limits"), "status": agg, "worst_case": worst})
    return out


def merge(manifest: dict, reports: Dict[str, dict], digests: Dict[str, str] = None) -> dict:
    """Concatenate per-process reports in canonical order; recompute aggregates only.

    `digests` (process -> request sha256 the caller actually submitted) is checked
    against the manifest; omit only in tests that exercise other gates.
    """
    check_manifest(manifest)
    want = [s["process"] for s in manifest["shards"]]
    extra = sorted(set(reports) - set(want))
    missing = [p for p in want if p not in reports]
    if extra or missing:
        raise ShardError(f"shard set mismatch: missing {missing}, unexpected {extra}")
    if digests is not None:
        for s in manifest["shards"]:
            if digests.get(s["process"]) != s["request_sha256"]:
                raise ShardError(f"{s['process']}: submitted request digest {digests.get(s['process'])} != manifest {s['request_sha256']}")
    corners: List[dict] = []
    seen: set = set()
    for s in manifest["shards"]:
        rep = reports[s["process"]]
        if not isinstance(rep, dict) or "error" in rep or not isinstance(rep.get("corners"), list):
            raise ShardError(f"{s['process']}: not a klt sim report with corners[]")
        got = []
        for c in rep["corners"]:
            sv = c.get("supply_v") or {}
            if c.get("process") != s["process"] or "vdd" not in sv:
                raise ShardError(f"{s['process']}: corner {c.get('corner_id')} is not of this shard")
            k = C.key_str(C.make_key(c["process"], c.get("temperature_c"), sv["vdd"]))
            if k in seen:
                raise ShardError(f"{k}: duplicate point across shards")
            seen.add(k)
            got.append(k)
        if sorted(got) != sorted(s["keys"]) or len(got) != len(s["keys"]):
            raise ShardError(f"{s['process']}: corners {sorted(got)} != expected {sorted(s['keys'])}")
        cov = rep.get("coverage")
        if not isinstance(cov, dict) or cov.get("nothing_checked") is not False or cov.get("skipped"):
            raise ShardError(f"{s['process']}: shard coverage not clean ({cov!r})")
        corners.extend(rep["corners"])
    order = {C.key_str(k): i for i, k in enumerate(C.expected_keys())}
    corners.sort(key=lambda c: order[C.key_str(C.make_key(c["process"], c["temperature_c"], c["supply_v"]["vdd"]))])
    first = reports[want[0]]
    merged = copy.deepcopy(first)
    merged["corners"] = corners
    merged["corner_count"] = len(corners)
    for st, field in (("pass", "passed"), ("fail", "failed"), ("error", "errored")):
        merged[field] = sum(1 for c in corners if c.get("status") == st)
    sts = {c.get("status") for c in corners}
    merged["status"] = "error" if sts - {"pass", "fail"} else "fail" if "fail" in sts else "pass"
    merged["metrics"] = {
        "sim__corner__count": len(corners),
        "sim__corner__passed_count": merged["passed"],
        "sim__corner__failed_count": merged["failed"],
        "sim__corner__errored_count": merged["errored"],
    }
    merged["measurements"] = rollup(first["measurements"], corners)
    cov = copy.deepcopy(first["coverage"])
    cov["nothing_checked"] = False
    cov["skipped"] = []
    cov["corners_simulated"] = len(corners)
    cov["checked"] = sorted({x for p in want for x in reports[p]["coverage"].get("checked", [])})
    cov["inapplicable"] = [x for p in want for x in reports[p]["coverage"].get("inapplicable", [])]
    merged["coverage"] = cov
    # Fields that are specific to one shard (its body's hash, its fleet job) must
    # not be left standing as if they described the whole grid: they move into
    # per-shard arrays.
    env = merged.setdefault("environment", {})
    env.pop("netlist_sha256", None)
    env["remote"] = {"fleet": [(reports[p].get("environment") or {}).get("remote") for p in want]}
    env["shard_netlist_sha256"] = {p: (reports[p].get("environment") or {}).get("netlist_sha256") for p in want}
    prov = merged.setdefault("provenance", {})
    prov.pop("input", None)
    prov["shard_input_content_hash"] = {p: ((reports[p].get("provenance") or {}).get("input") or {}).get("content_hash") for p in want}
    prov["shard_bridge"] = {
        "tool": "sim/cmrr-psrr/klt/shard.py",
        "master_request_sha256": manifest["master_request_sha256"],
        "shard_request_sha256": {s["process"]: s["request_sha256"] for s in manifest["shards"]},
        "reason": "runner image klt 0.5.0 (2AMLogic/2am#2193) cannot carry the one-request shape",
        "aggregates": "status/counts/metrics/measurements[] rollup recomputed over the 45 corners with klt sim's own rule; corners are unmodified",
    }
    return merged


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("gen")
    g.add_argument("--workdir", required=True)
    g.add_argument("--batch-pdk-root", default="/opt/pdk")
    m = sub.add_parser("merge")
    m.add_argument("--manifest", required=True)
    m.add_argument("-o", "--output", required=True)
    m.add_argument("reports", nargs="+", metavar="process=report.json")
    a = ap.parse_args(argv)
    try:
        if a.cmd == "gen":
            man = gen(a.workdir, a.batch_pdk_root)
            print(f"shard.py: wrote {len(man['shards'])} shard requests + shards.json to {a.workdir}")
            return 0
        with open(a.manifest) as f:
            manifest = json.load(f)
        mdir = os.path.dirname(os.path.abspath(a.manifest))
        reports: Dict[str, dict] = {}
        for arg in a.reports:
            proc, _, path = arg.partition("=")
            if proc in reports:
                raise ShardError(f"{proc}: shard given twice")
            with open(path) as f:
                reports[proc] = json.load(f)
        digests = {}
        for s in manifest["shards"]:
            with open(os.path.join(mdir, s["request"])) as f:
                digests[s["process"]] = _digest(json.load(f))
        merged = merge(manifest, reports, digests)
        with open(a.output, "w") as f:
            json.dump(merged, f, indent=2)
            f.write("\n")
        print(f"shard.py: merged {len(merged['corners'])} corners -> {a.output}")
        return 0
    except (ShardError, OSError, ValueError) as e:
        print(f"shard.py: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
